privatebin:
  ports:
  - name: privatebin-http
    port: 8080
    targetPort: 8080
  privatebin:
    image:
      repository: privatebin/nginx-fpm-alpine
      tag: 1.3.5
    resources:
      limits:
        cpu: 150m
        memory: 300Mi
      requests:
        cpu: 50m
        memory: 100Mi
  replicas: 1
  type: ClusterIP
