apiVersion: v1
kind: Service
metadata:
  name: {{ include "privatebin.fullname" . }}-privatebin
  labels:
    name: privatebin
  {{- include "privatebin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.privatebin.type }}
  selector:
    name: privatebin
  {{- include "privatebin.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.privatebin.ports | toYaml | nindent 2 -}}